[package]
name = "loqui_server"
version = "0.0.1"
authors = ["Discord Inc."]
edition = "2018"

[dependencies]
failure = "0.1.1"
log = "0.4"
futures = "0.1.25"
loqui_protocol = { path = "../loqui_protocol" }
loqui_connection = { path = "../loqui_connection" }
tokio = { version = "0.1.19", features = ["async-await-preview"] }
tokio-sync = "0.1.5"
serde = "1.0.27"
bytesize = "1.0.0"
tokio-codec = "0.1"
