[package]
name = "loqui_examples_echo"
version = "0.0.1"
authors = ["Discord Inc."]
edition = "2018"

[dependencies]
failure = "0.1.1"
futures = "0.1.25"
loqui_protocol = { path = "../../loqui_protocol" }
loqui_client = { path = "../../loqui_client" }
loqui_server = { path = "../../loqui_server" }
tokio = { version = "0.1.16", features = ["async-await-preview"] }
log = "0.4"
fern = "0.5"
chrono = "0.4"
serde = "1.0.27"
bytesize = "1.0.0"
futures-timer = "0.1"
serde_json = "1.0.9"
