[package]
name = "loqui_client"
version = "0.0.1"
authors = ["Discord Inc."]
edition = "2018"

[dependencies]
loqui_protocol = { path = "../loqui_protocol" }
loqui_connection = { path = "../loqui_connection" }
failure = "0.1.1"
log = "0.4"
futures = "0.1.25"
futures-timer = "0.1"
tokio = { version = "0.1.16", features = ["async-await-preview"] }
tokio-codec = "0.1"
tokio-io = { version = "0.1.12" }
serde = "1.0.27"
bytes = "0.4.9"
bytesize = "1.0.0"
tokio-async-await = "0.1.4"
tokio-current-thread = "0.1.6"
