[package]
name = "loqui_connection"
version = "0.0.1"
authors = ["Discord Inc."]
edition = "2018"

[dependencies]
failure = "0.1.1"
log = "0.4"
futures = "0.1.25"
loqui_protocol = { path = "../loqui_protocol" }
tokio = { version = "0.1.16", features = ["async-await-preview"] }
tokio-async-await = "0.1.6"
tokio-codec = "0.1"
futures-timer = "0.1"
serde = "1.0.27"
backoff = "0.1.2"
bytesize = "1.0.0"
