[package]
name = "loqui_bench_server"
version = "0.0.1"
authors = ["Discord Inc."]
edition = "2018"

[dependencies]
failure = "0.1.1"
futures = "0.1.25"
loqui_protocol = { path = "../../loqui_protocol" }
loqui_server = { path = "../../loqui_server" }
tokio = { version = "0.1.16", features = ["async-await-preview"] }
bytesize = "1.0.0"
loqui_bench_common = { path = "../common" }
